"""Attack the degree-zero sheaf comparison with exact shifted resolutions.

Owns:
    A hypersurface tensor with negative Tor, independent Hom and homotopy
    equations, and a positive-source Ext counterexample to overbroad rigidity.

Depends on:
    Existing exact polynomial arithmetic over Rational and Eisenstein.

Must not:
    Identify generic ring modules with a carrier or infer physical scalars.

Phase 0:
    Mathematical regressions for the human-readable truncation proof.
"""

import pytest

from onetheory.math.numbers import Eisenstein, Rational
from onetheory.math.polynomials import Polynomial, PolynomialMatrix


@pytest.mark.parametrize("field", (Rational, Eisenstein))
def test_negative_tor_does_not_add_a_degree_zero_sheaf_map(field):
    """C tensor C has Tor1=k[t]/t, but Hom0 to C has one scalar modulo t."""

    t = Polynomial.monomial((1,), scalar_type=field)
    one = Polynomial.one(1, scalar_type=field)
    coefficient = Rational(2) if field is Rational else Eisenstein(2, 1)
    c = one.scale(coefficient) + t**2
    h = one.scale(field(3)) + t
    # Cochain degrees -2,-1,0: d2=(-t,t), d1=(t,t).
    # ker d1 is generated by (-1,1); im d2 is t times it.
    d2, d1 = PolynomialMatrix(((-t,), (t,))), PolynomialMatrix(((t, t),))
    generator = PolynomialMatrix(((-one,), (one,)))
    assert d1.compose(d2).is_zero()
    assert d1.compose(generator).is_zero()
    assert one.coefficient((0,)) != field(0)  # the generator is not t-divisible
    target_d = PolynomialMatrix(((t,),))

    def comparison(value):
        # A degree-zero map has f0=c and f1=(a,b). Its chain
        # equation t(a,b)=(ct,ct) forces a=b=c in this domain.
        return PolynomialMatrix(((value,),)), PolynomialMatrix(((value, value),))

    f0, f1 = comparison(c)
    assert target_d.compose(f1) == f0.compose(d1)
    assert f1.compose(d2).is_zero()
    changed = PolynomialMatrix(((c + one, c - one),))
    assert target_d.compose(changed) != f0.compose(d1)
    assert changed.compose(d2).is_zero() is False

    # The only degree-minus-one homotopy is h: source0-to-target(-1).
    # It changes f0 by t*h and f1 by (t*h,t*h), not by a Tor parameter.
    g0, g1 = comparison(c + t * h)
    homotopy = PolynomialMatrix(((h,),))
    assert g0.rows[0][0] - f0.rows[0][0] == target_d.compose(homotopy).rows[0][0]
    difference = homotopy.compose(d1)
    assert tuple(g - f for g, f in zip(g1.rows[0], f1.rows[0], strict=True)) == (
        difference.rows[0]
    )
    assert g0.rows[0][0].coefficient((0,)) == f0.rows[0][0].coefficient((0,))


@pytest.mark.parametrize("field", (Rational, Eisenstein))
def test_positive_source_cohomology_can_contribute_an_ext_map(field):
    """Shifting k[t]/t to cohomological degree one invalidates the lemma."""

    t = Polynomial.monomial((1,), scalar_type=field)
    one = Polynomial.one(1, scalar_type=field)
    # Source [S --t--> S] is in cochain degrees 0,1: H0=0,
    # H1=S/t. Target's free resolution is in degrees -1,0.
    # A Hom0 cycle is any c: source0-to-target0. Its other
    # components are forced zero by the degree supports.
    coefficient = Rational(2) if field is Rational else Eisenstein(2, 1)
    c = one.scale(coefficient) + t
    assert not (t * c).is_zero()  # multiplication by t has zero kernel
    # Two possible homotopy components change c by t*h0+h1*t.
    h0, h1 = one.scale(field(3)), t + one
    boundary = t * h0 + h1 * t
    assert boundary.coefficient((0,)) == field(0)
    assert c.coefficient((0,)) != field(0)
    assert (c + boundary).coefficient((0,)) == c.coefficient((0,))
    # Thus c is not a Hom boundary despite H0(source)=0. These
    # are Ext1 maps, not the negative-degree ambient Tor case.
